### ISSUE TITLE
IP SCANNER LOGO

### ISSUE THREAD

**Issue by batarian71** [wcoder/IP-Scanner#1]
Hi,

I designed a logo for your application. I hope you liket it. Also, if you want, we can revise it.

![ip-scanner](https://user-images.githubusercontent.com/36008612/40281485-3348178e-5c6b-11e8-891d-c5c50faf30fb.jpg)

**Comment by wcoder** [comment]
Hi @batarian71 thank you for logos!

I think the first logo is better.
