### ISSUE TITLE
Use string IP instead of IpAddress?

### ISSUE THREAD

**Issue by AlphaNecron** [wcoder/IP-Scanner#3]
Why don't you do that? It's a lot easier than using IpAddress class...

**Comment by yauhenipakala** [comment]
Thanks for the question.

> Why don't you do that?

Just for fun :)

> Use string IP instead of IpAddress?

Main reason: objects over base primitive types
 - type-checking
 - avoid string manipulations

Also:
1. Simple validation (`IPAddress.Parse`)
2. Incrementing by octets

> a lot easier than using IpAddress

Can you provide an example?
